# Generated by Django 5.1.2 on 2024-11-01 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.CharField(default='name', max_length=100),
            preserve_default=False,
        ),
    ]
